
name: CI & CD
on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Runs a set of commands using the runners shell
      - name: build project
        run: |
          ls
          npm i
          npm run build
      
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v4.1.8
        with: 
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: 121.36.3.191
          REMOTE_USER: root
          SOURCE: dist/
          TARGET: /root/front-web/mfTest/baseApp
      
